exception: remove source_location indirect
clang-16 now natively supports std::source_location so we do not need
the experimental indirection.  Clean up the code.

Tested: Compiled with `CXX=clang++`.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Iabb10a603e1451228e27948fb0791b9db4791ec7