meson: fix -werror, tests and format
Dependent projects are compiled with -werror and failing because of this
dependency.

For example phosphor-bmc-code-mgmt.

```
../subprojects/stdplus/include/stdplus/net/addr/ip.hpp:550:26: error: space between quotes and suffix is deprecated in C++23 [-Werror=deprecated-literal-operator]
  550 | constexpr auto operator"" _ip() noexcept
      |                          ^~
      |                          --
```

Also apply meson format

test/io_uring.cpp had to be fixed because there was an access to an
optional which had been ```.reset()``` previously.

Tested: Unit Tests Pass

Change-Id: Iae8bff96cf69a82aea8c1964cfd35908946d7f47
Signed-off-by: Alexander Hansen <alexander.hansen@9elements.com>