exception: Use source_location instead of compiler builtins
Change-Id: I11df2559c89726516a317fe8e2edc359d8871343
Signed-off-by: William A. Kennington III <wak@google.com>