exception: Fix for older clang
Clang prior to 15 did not implement source_location and requires use of
an experimental header.

Change-Id: I14cc49cb36553397217143dcbb6d4c1dcd99fdbf
Signed-off-by: William A. Kennington III <wak@google.com>